language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libhdf5-serial-dev
 
install:
  - "pip install -r requirements.txt"
  - python setup.py install
  
# command to run tests
script: nosetests
