dist: trusty
sudo: false
language: python
python:
  - "2.7"

env:
  - PERCIVAL_CARRIER_IP=127.0.0.1

cache:
  directories:
    - $HOME/.cache/pip
#    - $HOME/virtualenv/python$TRAVIS_PYTHON_VERSION/lib/python$TRAVIS_PYTHON_VERSION/site-packages

addons:
  apt:
    packages:
      - libhdf5-serial-dev
      - libzmq3-dev
      - libatlas-base-dev liblapack-dev
 
before_install:
  - pip install wheel
  - pip install -r requirements.txt
  - pip install coveralls --upgrade --force-reinstall
  
install:
  - python setup.py install
  
# command to run tests
script: nosetests

after_success:
  - coveralls

